
# arrow

LINE_COLOR="lime"
LINE_WIDTH = 1

MARKER_SIZE=5
ARROW_MARKER_COLOR="yellow"

ON_HOVER_ARROW_MARKER_COLOR="palevioletred"



# text
ANNOTATION_BOX_FACE_COLOR="brown"
ANNOTATION_BOX_STYLE="round,pad=0.5"
ANNOTATION_TEXT_COLOR = "orange"
HOVER_ANNOTATION_TEXT_COLOR = "lime"
SELECTION_ANNOTATION_TEXT_COLOR = "red"
ANNOTATION_FONT_SIZE = 12
ANNOTATION_BOX_EDGE_COLOR="black"



# line

LINE_WIDTH = 1
MARKER_COLOR = "red"
HOVER_LINE_COLOR = "yellow"
HOVERED_MARKER_LINE_COLOR = "yellow"

HOVER_ANNOTATION_BACKGROUND_COLOR = "maroon"

# (HOVER MARKER)
HOVER_MARKER_LINE_COLOR = "lime"                   

GLOW_ANNOTATION_BOX_EDGE_COLOR="red"



# pencil


CLICKED_LINE_COLOR = "red"


# square
HOVER_MARKER_COLOR = "yellow"
HOVER_ANNOTATION_BOX_FACE_COLOR="yellow"
# ANNOTATION_TEXT_COLOR = "yellow"

ANNOTATION_BOX_FACE_COLOR = "brown"
HOVER_LINE_COLOR = "yellow"

SQUARE_SELECTED_COLOR = "red"
SELECTED_ANNOTATION_FACE_COLOR="red"
SELECTED_MARKER_COLOR="LIME"
FILL_COLOR="lime"
SQUARE_EDGE_COLOR="red"
RESET_SQUARE_EDGE_COLOR="lime"
SELECTED_MARKER_COLOR="LIME"





# ellipse

HOVER_LINE_COLOR = "yellow"


ELLIPSE_SELECTED_COLOR = "red"
ELLIPSE_EDGE_COLOR="red"
RESET_ELLIPSE_EDGE_COLOR="lime"


# angle

HOVER_ANNOTATION_BOX_EDGE_COLOR="red"


HIGHLIGHT_LINE_COLOUR="yellow"
HIGHLIGHT_MARKER_EDGE_COLOR="lime"
RESET_LINE_COLOUR="lime"
RESET_MARKER_EDGE_COLOR="red"
HIGHLIGHT_LINE_COLOUR1="red"

MARKER_EDGE_COLOR="lime"
ANGLE_LINE_COLOR="red"        #angle line color
DRAW_LINE_PRESS="lime"
DRAW_LINE_RELEASE="lime"



# open&close POLYGON
POLY_HOVER_MARKER_COLOR="hotpink"

POLY_HOVER_LINE_COLOR="red"



HOVER_ANNOTATION_BOX_EDGE_COLOR="red"


POLY_DESELECT_MARKER_COLOR="cornsilk"

POLY_GLOW_LINE_COLOR1="yellow"
POLY_GLOW_LINE_COLOR2="lime"
POLY_MARKER_SIZE =3